# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-node:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run: sudo apt-get update && sudo apt-get install rsync

      # Download and cache dependencies
      - restore_cache:
          keys:
          - root-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
          - garden-service-{{ checksum "garden-service/package-lock.json" }}
      # Install npm deps
      - run: npm ci
      - run: node_modules/.bin/lerna bootstrap --ci
      - save_cache:
          paths: [node_modules]
          key: root-{{ checksum "package-lock.json" }}
      - save_cache:
          paths: [garden-service/node_modules]
          key: garden-service-{{ checksum "garden-service/package-lock.json" }}

      - run:
          name: Make sure generated docs are up-to-date
          command: |
            npm run generate-docs
            npm run check-docs

      # build, lint and run tests
      - run:
          name: npm build
          command: npm run build
      - run:
          name: npm lint
          command: npm run lint
      - run:
          name: npm test
          command: npm test

workflows:
 version: 2
 all-tests:
   jobs:
     - test-node
