# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
.references:
  go-config: &go-config
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/garden-io/garden

commands:
  go_install_deps:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - restore_cache:
          keys:
            - pkg-cache-{{ checksum "Gopkg.lock" }}
      - run: go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Install dep
          command: |
            if [ ! -d /go/src/github.com/garden-io/garden/vendor ]; then
                curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o /go/bin/dep
                chmod +x /go/bin/dep
                /go/bin/dep ensure
            fi
      - save_cache:
          key: pkg-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - "/go/src/github.com/garden-io/garden/vendor"
version: 2.1
jobs:
  test-go:
    <<: *go-config
    steps:
      - checkout
      - go_install_deps
      - run:
          name: Unit Tests
          command: |
            cd garden-cli
            go test -v 2>&1 | go-junit-report > /tmp/report.xml
      - store_artifacts:
          path: /tmp/report.xml
      - store_test_results:
          path: /tmp/
  build-go:
    <<: *go-config
    steps:
      - checkout
      - go_install_deps
      - run: go get -u github.com/goreleaser/goreleaser
      - run: cd garden-cli && goreleaser --snapshot --rm-dist
      - store_artifacts:
          path: garden-cli/dist/
          destination: /downloads
  test-node:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install rsync
      - setup_remote_docker:
          docker_layer_caching: true
      # Download and cache dependencies
      - restore_cache:
          keys:
          - root-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
          - garden-service-{{ checksum "garden-service/package-lock.json" }}

      - run: git submodule update --init --recursive

      # only install if node_modules wasn't cached
      - run: if [ ! -d "node_modules" ]; then npm ci; fi
      - save_cache:
          paths: [node_modules]
          key: root-{{ checksum "package-lock.json" }}

      - run: cd garden-service && npm install
      - save_cache:
          paths: [garden-service/node_modules]
          key: garden-service-{{ checksum "garden-service/package-lock.json" }}

      - run:
          name: build
          command: npm run ci-build

      - run:
          name: Make sure generated docs are up-to-date
          command: npm run check-docs

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: npm run ci-test

workflows:
 version: 2
 all-tests:
   jobs:
     - test-go
     - build-go
     #- test-node
